/** Known `app_config.key` values for public metadata lookups */
export const CONFIG_TYPES = [
  "ideal_job_titles",
  "salary_preference_range",
  "job_types",
  "job_creation_roles",
  "favourite_work_vibe",
  "cancellation_policies",
  "working_hours",
  "interview_types",
  "documents_required",
  "types_of_clinics",
  "compliance_documents",
  "years_of_experience",
  "job_current_status",
  "benefits_offered",
  "overtime_rules",
  "specialisations",
  "pay_ranges",
  "specialisms",
  "looking_for",
  "job_creation_job_types",
  "job_creation_benefits",
  "education",
  "rate_types",
  "role_based_skills",
  "preferred_working_patterns",
  "payment_terms",
  "skills_required",
  "experience_levels",
  "contract_types",
  "software_required",
  "work_load",
  "working_super_power",
  "salary_ranges",
  "tackling_difficult_situation",
  "job_titles",
] as const;

/** Snake_case config key accepted by `GET /v2/config/{type}` */
export type ConfigType = (typeof CONFIG_TYPES)[number];
